
spring:
  datasource:
    url: jdbc:mysql://192.168.56.10:3306/gulimall_ums?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.10:8848
  application:
    name: gulimall-member
  redis:
    host: 192.168.56.10
    port: 6379
mybatis-plus:
  #classpath*表示扫描包括引入的其他包下的mapper映射文件
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      #设置主键自增
      id-type: auto
server:
  port: 8000