
spring:
  datasource:
    url: jdbc:mysql://192.168.56.10:3306/gulimall_sms?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.10:8848
  application:
    name: gulimall-coupon
  jackson:
    date-format: yyyy-MM-dd HH-mm-ss
  task:
    execution:
      pool:
        core-size: 20
        max-size: 50
        queue-capacity: 100000 #异步线程池队列长度
mybatis-plus:
  #classpath*表示扫描包括引入的其他包下的mapper映射文件
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      #设置主键自增
      id-type: auto
server:
  port: 7000
